"""
Tool: pdf_export

Generates a formatted PDF meal plan document.
"""

from __future__ import annotations

from io import BytesIO

from fpdf import FPDF


def generate_meal_plan_pdf(
    recipes: list[dict],
    grocery_list: dict[str, list[str]],
    nutrition_summary: dict,
    budget_estimate: dict | None = None,
) -> bytes:
    """Generate a PDF meal plan and return it as bytes."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "Weekly Meal Plan", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, "Generated by MealPlanAgent", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Meals", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    for i, recipe in enumerate(recipes):
        day = recipe.get("_day", days[i % 7])
        name = recipe.get("name", "Unknown Recipe")
        minutes = recipe.get("minutes", 0)
        citation = recipe.get("citation", {})

        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, f"{day}: {name} ({minutes} min)", new_x="LMARGIN", new_y="NEXT")

        ingredients = recipe.get("ingredients", [])
        if ingredients:
            pdf.set_font("Helvetica", "", 9)
            ing_text = ", ".join(ingredients[:15])
            if len(ingredients) > 15:
                ing_text += "..."
            pdf.multi_cell(0, 5, f"  Ingredients: {ing_text}")

        if citation.get("recipe_id"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, f"  Source: {citation.get('source', 'Food.com')} | ID: {citation['recipe_id']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Grocery List", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    for category, items in grocery_list.items():
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, category, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for item in items:
            safe_item = item.encode("latin-1", "replace").decode("latin-1")
            pdf.cell(0, 5, f"  - {safe_item}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    if budget_estimate:
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Estimated Budget", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        total = budget_estimate.get("total_estimated_cost", 0)
        pdf.cell(0, 7, f"Total Estimated Cost: ${total:.2f}", new_x="LMARGIN", new_y="NEXT")
        for cat, cost in budget_estimate.get("per_category", {}).items():
            pdf.cell(0, 6, f"  {cat}: ${cost:.2f}", new_x="LMARGIN", new_y="NEXT")

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Nutrition Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 10)
    for nutrient, value in nutrition_summary.items():
        unit = "kcal" if "calorie" in nutrient.lower() else ("mg" if "sodium" in nutrient.lower() else "g")
        pdf.cell(0, 7, f"  {nutrient}: {value:.1f} {unit}", new_x="LMARGIN", new_y="NEXT")

    buffer = BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
